// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpSkill_API.Contexts;

#nullable disable

namespace UpSkill_API.Migrations
{
    [DbContext(typeof(StudentsContext))]
    partial class StudentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UpSkill_API.Models.StudentsModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("AreaOfNeed")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalAgencies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KamarUpdates")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtherInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pronoun")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Response")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("SAC")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SACInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tutor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
